name: nimbus_2K25
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+9

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dio: ^5.8.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.0.0
  image_picker: ^1.1.2
  image_picker_platform_interface: ^2.10.1
  flutter_launcher_icons: ^0.14.3
  shimmer: ^3.0.0
  location: ^8.0.0
  flutter_riverpod: ^2.6.1
  flutter_map: ^8.1.0
  permission_handler: ^11.0.1
  qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  http: ^1.3.0
  lottie: ^3.3.0
  flutter_carousel_widget: ^2.1.1
  dots_indicator: ^4.0.1
  flutter_carousel_slider: ^1.1.0

 

dependency_overrides:
  carousel_slider: 4.2.0
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/Beige Floral Page Border_20250304_223925_0000 1 (4).png
    - assets/Animation - 1742550809348.json
    - assets/Animation - 1742550054765.json
    - assets/profile-circled.512x512.png
    - assets/image 5 (3).png
    - assets/icons8-pay-48 1.png
    - assets/Icon (9).png
    - assets/Icon (8).png
    - assets/Beige Floral Page Border_20250304_223925_0000 1 (1).png
    - assets/Beige Floral Page Border_20250304_223925_0000 1.png
    - assets/Beige Floral Page Border_20250304_223925_0000.png
    - assets/WhatsApp Image 2025-03-04 at 22.28.21.jpeg
    - assets/pngegg (1) 1.png
    - assets/pngegg (1).png
    - assets/3ef54ebf9a970c2c3e86dbd4e9caf522.png
    - assets/Icon (4).png
    - assets/Icon (6).png
    - assets/Mask group.png
    - assets/Ellipse 873.png
    - assets/Ellipse 873 (1).png
    - assets/Essential - money (PNG).png
    - assets/Rectangle 4191 (1).png
    - assets/Divider.png
    - assets/Icon (1).png
    - assets/k.png
    - assets/Icon (3).png
    - assets/Ellipse 390 (2).png
    - assets/Essential - money (PNG) (1).png
    - assets/Rectangle 4191.png
    - assets/Icon (2).png
    - assets/buttonOutlinedStandard (2).png
    - assets/Essential - Emotion workflow man (PNG).png
    - assets/Essential - a man holding phone and social icons around him (PNG) (5).png
    - assets/Essential - a man holding phone and social icons around him (PNG) (2).png
    - assets/Essential - a man holding phone and social icons around him (PNG).png
    - assets/Essential - a man holding phone and social icons around him (PNG) (1).png
    - assets/A modern conference room filled with attendees engaged in discussions about technology and innovation..png
    - assets/memphis_problem_solving.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Beige Floral Page Border_20250304_223925_0000 1 (4).png"